name: dartx
description: Superpowers for Dart. Collection of useful static extension methods.
version: 0.5.0
homepage: https://github.com/leisim/dartx

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.5
  path: ^1.8.0-nullsafety.3
  crypto: 
  characters: ^1.1.0-nullsafety.5 
  time: ^1.5.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  pedantic: ^1.10.0-nullsafety.3
  fake_async: ^1.2.0-nullsafety.3
