name: testx
description: WIP
version: 0.0.0
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/dartx

environment:
  sdk: ">=2.6.0-dev.5.0 <3.0.0"

dependencies:
  test: any
