name: Dart CI

on: [push, pull_request]

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Install dart
        run: |
          choco install dart-sdk
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: C:\tools\dart-sdk\bin\pub.bat get
      - name: Run tests
        run: C:\tools\dart-sdk\bin\pub.bat run test

  test:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:dev

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
