name: Dart CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:dev
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
      working-directory: dartx
    - name: Run tests
      run: pub run test
      working-directory: dartx
      
  coverage:
    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:dev
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
      working-directory: dartx
    - name: Collect coverage
      run: |
        pub global activate test_coverage
        pub global run test_coverage
      working-directory: dartx
    - uses: codecov/codecov-action@v1.0.0	
      with:
        token: ${{ secrets.CODECOV_TOKEN }}	
        file: dartx/coverage/lcov.info
